Adds collision messages to killfeed
HannesTuhkala/plen pull request #104
Opened 2019-12-03 19:22 UTC by HannesTuhkala

2019-12-03 19:32 UTC, Emiluren requested changes

2019-12-03 19:32 UTC, Emiluren commented on libplen/src/gamestate.rs
> +                    //&& !collided_players.contains(&p1.id) {
Outcommented code. Pls remove

2019-12-04 00:20 UTC, HannesTuhkala commented on libplen/src/gamestate.rs
> +                    //&& !collided_players.contains(&p1.id) {
It's now removed

2019-12-04 09:39 UTC, malcx95 commented on libplen/src/constants.rs
> +pub const HURRICANE_PROBABILITY: f32 = 0.005;
I think this reduction is too much

2019-12-04 10:42 UTC, Emiluren approved these changes

2019-12-04 11:44 UTC, TheZoq2 commented
![image](https://user-images.githubusercontent.com/5312813/70139892-cb000080-1693-11ea-90cf-2a5563e8a47a.png)
:thinking:

2019-12-04 11:45 UTC, TheZoq2 approved these changes

2019-12-05 14:14 UTC, merged