Sdl rendering
HannesTuhkala/plen pull request #87
Opened 2019-11-23 21:38 UTC by Emiluren

2019-11-23 21:38 UTC, HannesTuhkala approved these changes

2019-11-23 22:01 UTC, HannesTuhkala requested changes
Not tested on Windows yet

2019-11-24 09:01 UTC, TheZoq2 requested changes
Looks good apart from a few style issues

2019-11-24 09:01 UTC, TheZoq2 commented on Cargo.toml
> +serde_derive = "1.0.102"
Are these used in the client/server again? Previously the were only used in libplen

2019-11-24 09:01 UTC, TheZoq2 commented on Cargo.toml
> +strum_macros = "0.16.0"
Same thing with strum

2019-11-24 09:01 UTC, TheZoq2 commented on libplen/src/constants.rs
> +pub const POWERUP_SPEED: f32 = 1.8;
#83 changed this to 1.5

2019-11-24 09:01 UTC, TheZoq2 commented on src/map.rs
>          for message in messages.iter() {
use `for (i, message) = messages.iter().enumerate()` instead of `mut i = 0`

2019-11-24 09:01 UTC, TheZoq2 commented on src/menu.rs
> +        ).blended((255, 255, 255)).expect("Could not render text");
Weird indentation, I would prefer

```rust
assets.font.render(self.plane_name())
    .blended((255, 255, 255))
    .expect("Could not render text")
```

2019-11-24 09:01 UTC, TheZoq2 commented on src/menu.rs
> +        ).blended((255, 255, 255)).expect("Could not render text");
Same thing here

2019-11-24 09:01 UTC, TheZoq2 commented on src/menu.rs
> +        ).blended((255, 255, 255)).expect("Could not render text");
And here

2019-11-24 10:29 UTC, TheZoq2 approved these changes

2019-11-24 10:29 UTC, TheZoq2 approved these changes

2019-11-24 10:52 UTC, malcx95 approved these changes

2019-11-24 13:21 UTC, malcx95 requested changes
Name tags are no longer centered. It would be nice if you fixed this.

2019-11-24 14:43 UTC, Emiluren commented on Cargo.toml
> +serde_derive = "1.0.102"
Oops, must have slipped in with the merge conflict

2019-11-24 14:43 UTC, Emiluren commented on libplen/src/constants.rs
> +pub const POWERUP_SPEED: f32 = 1.8;
You're thinking of the wrong value POWERUP_SPEED_BOOST, not POWERUP_SPEED

2019-11-24 14:43 UTC, Emiluren commented on src/menu.rs
> +        ).blended((255, 255, 255)).expect("Could not render text");
Yes, I was thinking that we would need to cache the rendered strings for performance reasons so I just made some throwaway code but then it seemed to be fine performance wise. Will fix

2019-11-24 14:43 UTC, Emiluren commented on src/map.rs
>          for message in messages.iter() {
I wasn't the one who wrote this code originally but sure, I can fix it :P

2019-11-24 15:37 UTC, malcx95 approved these changes

2019-11-24 18:11 UTC, HannesTuhkala approved these changes
Works on Windows

2019-11-24 18:13 UTC, merged